/*
 * glfx.js
 * http://evanw.github.com/glfx.js/
 *
 * Copyright 2011 Evan Wallace
 * Copyright 2014 Pierre-Loic Doulcet (hexapode)
 * Copyright 2019 Joachim de Fourestier (joedf)
 * Released under the MIT license
 */
var fx=function(){function n(a,d,c){return Math.max(a,Math.min(d,c))}function x(b){return{_:b,loadContentsOf:function(b){a=this._.gl;this._.loadContentsOf(b)},destroy:function(){a=this._.gl;this._.destroy()}}}function B(a){return x(q.fromElement(a))}function C(b,d){var c=a.UNSIGNED_BYTE;if(a.getExtension("OES_texture_float")&&a.getExtension("OES_texture_float_linear")){var e=new q(100,100,a.RGBA,a.FLOAT);try{e.drawTo(function(){c=a.FLOAT})}catch(k){}e.destroy()}this._.texture&&this._.texture.destroy();
this._.spareTexture&&this._.spareTexture.destroy();this.width=b;this.height=d;this._.texture=new q(b,d,a.RGBA,c);this._.spareTexture=new q(b,d,a.RGBA,c);this._.extraTexture=this._.extraTexture||new q(0,0,a.RGBA,c);this._.flippedShader=this._.flippedShader||new h(null,"uniform sampler2D texture;varying vec2 texCoord;void main(){gl_FragColor=texture2D(texture,vec2(texCoord.x,1.0-texCoord.y));}");this._.isInitialized=!0}function D(a,d,c){this._.isInitialized&&
a._.width==this.width&&a._.height==this.height||C.call(this,d?d:a._.width,c?c:a._.height);a._.use();this._.texture.drawTo(function(){h.getDefaultShader().drawRect()});return this}function E(){this._.texture.use();this._.flippedShader.drawRect();return this}function g(a,d,c,e){(c||this._.texture).use();this._.spareTexture.drawTo(function(){a.uniforms(d).drawRect()});this._.spareTexture.swapWith(e||this._.texture)}function F(a){a.parentNode.insertBefore(this,a);a.parentNode.removeChild(a);return this}
function G(){var b=new q(this._.texture.width,this._.texture.height,a.RGBA,a.UNSIGNED_BYTE);this._.texture.use();b.drawTo(function(){h.getDefaultShader().drawRect()});return x(b)}function H(){var b=this._.texture.width,d=this._.texture.height,c=new Uint8Array(b*d*4);this._.texture.drawTo(function(){a.readPixels(0,0,b,d,a.RGBA,a.UNSIGNED_BYTE,c)});return c}function f(b){return function(){a=this._.gl;return b.apply(this,arguments)}}function y(a,d,c,e,k,l,m,h){var b=c-k,g=e-l,f=m-k,t=h-l;k=a-c+k-m;l=
d-e+l-h;var n=b*t-f*g;f=(k*t-f*l)/n;b=(b*l-k*g)/n;return[c-a+f*c,e-d+f*e,f,m-a+b*m,h-d+b*h,b,a,d,1]}function z(a){var b=a[0],c=a[1],e=a[2],k=a[3],l=a[4],m=a[5],f=a[6],h=a[7];a=a[8];var g=b*l*a-b*m*h-c*k*a+c*m*f+e*k*h-e*l*f;return[(l*a-m*h)/g,(e*h-c*a)/g,(c*m-e*l)/g,(m*f-k*a)/g,(b*a-e*f)/g,(e*k-b*m)/g,(k*h-l*f)/g,(c*f-b*h)/g,(b*l-c*k)/g]}function A(a){var b=a.length;this.xa=[];this.ya=[];this.u=[];this.y2=[];a.sort(function(a,b){return a[0]-b[0]});for(var c=0;c<b;c++)this.xa.push(a[c][0]),this.ya.push(a[c][1]);
this.u[0]=0;this.y2[0]=0;for(c=1;c<b-1;++c){a=this.xa[c+1]-this.xa[c-1];var e=(this.xa[c]-this.xa[c-1])/a,k=e*this.y2[c-1]+2;this.y2[c]=(e-1)/k;this.u[c]=(6*((this.ya[c+1]-this.ya[c])/(this.xa[c+1]-this.xa[c])-(this.ya[c]-this.ya[c-1])/(this.xa[c]-this.xa[c-1]))/a-e*this.u[c-1])/k}this.y2[b-1]=0;for(c=b-2;0<=c;--c)this.y2[c]=this.y2[c]*this.y2[c+1]+this.u[c]}function v(a,d){return new h(null,a+"uniform sampler2D texture;uniform vec2 texSize;varying vec2 texCoord;void main(){vec2 coord=texCoord*texSize;"+
d+"gl_FragColor=texture2D(texture,coord/texSize);vec2 clampedCoord=clamp(coord,vec2(0.0),texSize);if(coord!=clampedCoord){gl_FragColor.a*=max(0.0,1.0-length(coord-clampedCoord));}}")}function I(b,d){a.brightnessContrast=a.brightnessContrast||new h(null,"uniform sampler2D texture;uniform float brightness;uniform float contrast;varying vec2 texCoord;void main(){vec4 color=texture2D(texture,texCoord);color.rgb+=brightness;if(contrast>0.0){color.rgb=(color.rgb-0.5)/(1.0-contrast)+0.5;}else{color.rgb=(color.rgb-0.5)*(1.0+contrast)+0.5;}gl_FragColor=color;}");
g.call(this,a.brightnessContrast,{brightness:n(-1,b,1),contrast:n(-1,d,1)});return this}function J(b,d,c,e){a.color=a.color||new h(null,"uniform sampler2D texture;uniform float r;uniform float g;uniform float b;uniform float a;varying vec2 texCoord;void main(){vec4 color=texture2D(texture,texCoord);color.r+=r*a;color.g+=g*a;color.b+=b*a;gl_FragColor=color;}");
g.call(this,a.color,{r:d,g:c,b:e,a:b});return this}function K(b,d,c,e,k,l){a.coloradjust=a.coloradjust||new h(null,"uniform sampler2D texture;uniform float rmin;uniform float rmax;uniform float gmin;uniform float gmax;uniform float bmin;uniform float bmax;varying vec2 texCoord;void main(){vec4 color=texture2D(texture,texCoord);color.r=color.r*((rmax-rmin)/1.0)+rmin;color.g=color.g*((gmax-gmin)/1.0)+gmin;color.b=color.b*((bmax-bmin)/1.0)+bmin;gl_FragColor=color;}");
g.call(this,a.coloradjust,{rmin:b/255,rmax:d/255,gmin:c/255,gmax:e/255,bmin:k/255,bmax:l/255});return this}function u(a){a=new A(a);for(var b=[],c=0;256>c;c++)b.push(n(0,Math.floor(256*a.interpolate(c/255)),255));return b}function L(b,d,c){b=u(b);1==arguments.length?d=c=b:(d=u(d),c=u(c));for(var e=[],k=0;256>k;k++)e.splice(e.length,0,b[k],d[k],c[k],255);this._.extraTexture.initFromBytes(256,1,e);this._.extraTexture.use(1);a.curves=a.curves||new h(null,"uniform sampler2D texture;uniform sampler2D map;varying vec2 texCoord;void main(){vec4 color=texture2D(texture,texCoord);color.r=texture2D(map,vec2(color.r)).r;color.g=texture2D(map,vec2(color.g)).g;color.b=texture2D(map,vec2(color.b)).b;gl_FragColor=color;}");
a.curves.textures({map:1});g.call(this,a.curves,{});return this}function M(b){a.denoise=a.denoise||new h(null,"uniform sampler2D texture;uniform float exponent;uniform float strength;uniform vec2 texSize;varying vec2 texCoord;void main(){vec4 center=texture2D(texture,texCoord);vec4 color=vec4(0.0);float total=0.0;for(float x=-4.0;x<=4.0;x+=1.0){for(float y=-4.0;y<=4.0;y+=1.0){vec4 sample=texture2D(texture,texCoord+vec2(x,y)/texSize);float weight=1.0-abs(dot(sample.rgb-center.rgb,vec3(0.25)));weight=pow(weight,exponent);color+=sample*weight;total+=weight;}}gl_FragColor=color/total;}");
for(var d=0;2>d;d++)g.call(this,a.denoise,{exponent:Math.max(0,b),texSize:[this.width,this.height]});return this}function N(b){a.exposure=a.exposure||new h(null,"varying vec2 texCoord;uniform sampler2D texture;uniform highp float exposure;void main(){vec4 textureColor=texture2D(texture,texCoord);gl_FragColor=vec4(textureColor.rgb*pow(2.0,exposure),textureColor.a);}");g.call(this,a.exposure,{exposure:b});return this}
function O(b){a.gamma=a.gamma||new h(null,"varying vec2 texCoord;uniform sampler2D texture;uniform highp float gamma;void main(){vec4 color=texture2D(texture,texCoord);color.r=pow(color.r,gamma);color.g=pow(color.g,gamma);color.b=pow(color.b,gamma);gl_FragColor=color;}");g.call(this,a.gamma,{gamma:b});return this}function P(b,d,c,e,k,l,m,f,p){a.gammaRGB=a.gammaRGB||new h(null,
"varying vec2 texCoord;uniform sampler2D texture;uniform highp float amplitudeR;uniform highp float amplitudeG;uniform highp float amplitudeB;uniform highp float exponentR;uniform highp float exponentG;uniform highp float exponentB;uniform highp float offsetR;uniform highp float offsetG;uniform highp float offsetB;void main(){vec4 color=texture2D(texture,texCoord);color.r=amplitudeR*pow(color.r,exponentR)+offsetR;color.g=amplitudeG*pow(color.g,exponentG)+offsetG;color.b=amplitudeB*pow(color.b,exponentB)+offsetB;gl_FragColor=color;}");
g.call(this,a.gammaRGB,{amplitudeR:b,amplitudeG:e,amplitudeB:m,exponentR:d,exponentG:k,exponentB:f,offsetR:c,offsetG:l,offsetB:p});return this}function Q(b){a.hue=a.hue||new h(null,"uniform sampler2D texture;uniform float hue;varying vec2 texCoord;void main(){vec4 color=texture2D(texture,texCoord);float angle=hue*3.14159265;float s=sin(angle),c=cos(angle);vec3 weights=(vec3(2.0*c,-sqrt(3.0)*s-c,sqrt(3.0)*s-c)+1.0)/3.0;float len=length(color.rgb);color.rgb=vec3(dot(color.rgb,weights.xyz),dot(color.rgb,weights.zxy),dot(color.rgb,weights.yzx));gl_FragColor=color;}");
g.call(this,a.hue,{hue:b});return this}function R(b,d){a.hueSaturation=a.hueSaturation||new h(null,"uniform sampler2D texture;uniform float hue;uniform float saturation;varying vec2 texCoord;void main(){vec4 color=texture2D(texture,texCoord);float angle=hue*3.14159265;float s=sin(angle),c=cos(angle);vec3 weights=(vec3(2.0*c,-sqrt(3.0)*s-c,sqrt(3.0)*s-c)+1.0)/3.0;float len=length(color.rgb);color.rgb=vec3(dot(color.rgb,weights.xyz),dot(color.rgb,weights.zxy),dot(color.rgb,weights.yzx));float average=(color.r+color.g+color.b)/3.0;if(saturation>0.0){color.rgb+=(average-color.rgb)*(1.0-1.0/(1.001-saturation));}else{color.rgb+=(average-color.rgb)*(-saturation);}gl_FragColor=color;}");
g.call(this,a.hueSaturation,{hue:n(-1,b,1),saturation:n(-1,d,1)});return this}function S(b){a.noise=a.noise||new h(null,"uniform sampler2D texture;uniform float amount;varying vec2 texCoord;float rand(vec2 co){return fract(sin(dot(co.xy,vec2(12.9898,78.233)))*43758.5453);}void main(){vec4 color=texture2D(texture,texCoord);float diff=(rand(texCoord)-0.5)*amount;color.r+=diff;color.g+=diff;color.b+=diff;gl_FragColor=color;}");
g.call(this,a.noise,{amount:n(0,b,1)});return this}function T(b){a.sepia=a.sepia||new h(null,"uniform sampler2D texture;uniform float amount;varying vec2 texCoord;void main(){vec4 color=texture2D(texture,texCoord);float r=color.r;float g=color.g;float b=color.b;color.r=min(1.0,(r*(1.0-(0.607*amount)))+(g*(0.769*amount))+(b*(0.189*amount)));color.g=min(1.0,(r*0.349*amount)+(g*(1.0-(0.314*amount)))+(b*0.168*amount));color.b=min(1.0,(r*0.272*amount)+(g*0.534*amount)+(b*(1.0-(0.869*amount))));gl_FragColor=color;}");
g.call(this,a.sepia,{amount:n(0,b,1)});return this}function U(b){a.softContrast=a.softContrast||new h(null,"uniform sampler2D texture;uniform float contrast;varying vec2 texCoord;void main(){vec4 color=texture2D(texture,texCoord);color.r=(color.r-0.5)*contrast+0.5;color.g=(color.g-0.5)*contrast+0.5;color.b=(color.b-0.5)*contrast+0.5;gl_FragColor=color;}");g.call(this,
a.softContrast,{contrast:b});return this}function V(b,d){a.unsharpMask=a.unsharpMask||new h(null,"uniform sampler2D blurredTexture;uniform sampler2D originalTexture;uniform float strength;uniform float threshold;varying vec2 texCoord;void main(){vec4 blurred=texture2D(blurredTexture,texCoord);vec4 original=texture2D(originalTexture,texCoord);gl_FragColor=mix(blurred,original,1.0+strength);}");
this._.extraTexture.ensureFormat(this._.texture);this._.texture.use();this._.extraTexture.drawTo(function(){h.getDefaultShader().drawRect()});this._.extraTexture.use(1);this.triangleBlur(b);a.unsharpMask.textures({originalTexture:1});g.call(this,a.unsharpMask,{strength:d});this._.extraTexture.unuse(1);return this}function W(b){a.vibrance=a.vibrance||new h(null,"uniform sampler2D texture;uniform float amount;varying vec2 texCoord;void main(){vec4 color=texture2D(texture,texCoord);float average=(color.r+color.g+color.b)/3.0;float mx=max(color.r,max(color.g,color.b));float amt=(mx-average)*(-amount*3.0);color.rgb=mix(color.rgb,vec3(mx),amt);gl_FragColor=color;}");
g.call(this,a.vibrance,{amount:n(-1,b,1)});return this}function X(b,d){a.vignette=a.vignette||new h(null,"uniform sampler2D texture;uniform float size;uniform float amount;varying vec2 texCoord;void main(){vec4 color=texture2D(texture,texCoord);float dist=distance(texCoord,vec2(0.5,0.5));color.rgb*=smoothstep(0.8,size*0.799,dist*(amount+size));gl_FragColor=color;}");
g.call(this,a.vignette,{size:n(0,b,1),amount:n(0,d,1)});return this}function Y(b,d,c){a.lensBlurPrePass=a.lensBlurPrePass||new h(null,"uniform sampler2D texture;uniform float power;varying vec2 texCoord;void main(){vec4 color=texture2D(texture,texCoord);color=pow(color,vec4(power));gl_FragColor=vec4(color);}");var e="uniform sampler2D texture0;uniform sampler2D texture1;uniform vec2 delta0;uniform vec2 delta1;uniform float power;varying vec2 texCoord;"+
r+"vec4 sample(vec2 delta){float offset=random(vec3(delta,151.7182),0.0);vec4 color=vec4(0.0);float total=0.0;for(float t=0.0;t<=30.0;t++){float percent=(t+offset)/30.0;color+=texture2D(texture0,texCoord+delta*percent);total+=1.0;}return color/total;}";
a.lensBlur0=a.lensBlur0||new h(null,e+"void main(){gl_FragColor=sample(delta0);}");a.lensBlur1=a.lensBlur1||new h(null,e+"void main(){gl_FragColor=(sample(delta0)+sample(delta1))*0.5;}");a.lensBlur2=a.lensBlur2||(new h(null,e+"void main(){vec4 color=(sample(delta0)+2.0*texture2D(texture1,texCoord))/3.0;gl_FragColor=pow(color,vec4(power));}")).textures({texture1:1});e=
[];for(var k=0;3>k;k++){var l=c+k*Math.PI*2/3;e.push([b*Math.sin(l)/this.width,b*Math.cos(l)/this.height])}b=Math.pow(10,n(-1,d,1));g.call(this,a.lensBlurPrePass,{power:b});this._.extraTexture.ensureFormat(this._.texture);g.call(this,a.lensBlur0,{delta0:e[0]},this._.texture,this._.extraTexture);g.call(this,a.lensBlur1,{delta0:e[1],delta1:e[2]},this._.extraTexture,this._.extraTexture);g.call(this,a.lensBlur0,{delta0:e[1]});this._.extraTexture.use(1);g.call(this,a.lensBlur2,{power:1/b,delta0:e[2]});
return this}function Z(b,d,c,e,k,l){a.tiltShift=a.tiltShift||new h(null,"uniform sampler2D texture;uniform float blurRadius;uniform float gradientRadius;uniform vec2 start;uniform vec2 end;uniform vec2 delta;uniform vec2 texSize;varying vec2 texCoord;"+r+"void main(){vec4 color=vec4(0.0);float total=0.0;float offset=random(vec3(12.9898,78.233,151.7182),0.0);vec2 normal=normalize(vec2(start.y-end.y,end.x-start.x));float radius=smoothstep(0.0,1.0,abs(dot(texCoord*texSize-start,normal))/gradientRadius)*blurRadius;for(float t=-30.0;t<=30.0;t++){float percent=(t+offset-0.5)/30.0;float weight=1.0-abs(percent);vec4 sample=texture2D(texture,texCoord+delta/texSize*percent*radius);sample.rgb*=sample.a;color+=sample*weight;total+=weight;}gl_FragColor=color/total;gl_FragColor.rgb/=gl_FragColor.a+0.00001;}");
var m=c-b,f=e-d,p=Math.sqrt(m*m+f*f);g.call(this,a.tiltShift,{blurRadius:k,gradientRadius:l,start:[b,d],end:[c,e],delta:[m/p,f/p],texSize:[this.width,this.height]});g.call(this,a.tiltShift,{blurRadius:k,gradientRadius:l,start:[b,d],end:[c,e],delta:[-f/p,m/p],texSize:[this.width,this.height]});return this}function aa(b){a.triangleBlur=a.triangleBlur||new h(null,"uniform sampler2D texture;uniform vec2 delta;varying vec2 texCoord;"+r+"void main(){vec4 color=vec4(0.0);float total=0.0;float offset=random(vec3(12.9898,78.233,151.7182),0.0);for(float t=-30.0;t<=30.0;t++){float percent=(t+offset-0.5)/30.0;float weight=1.0-abs(percent);vec4 sample=texture2D(texture,texCoord+delta*percent);sample.rgb*=sample.a;color+=sample*weight;total+=weight;}gl_FragColor=color/total;gl_FragColor.rgb/=gl_FragColor.a+0.00001;}");
g.call(this,a.triangleBlur,{delta:[b/this.width,0]});g.call(this,a.triangleBlur,{delta:[0,b/this.height]});return this}function ba(b,d,c){a.zoomBlur=a.zoomBlur||new h(null,"uniform sampler2D texture;uniform vec2 center;uniform float strength;uniform vec2 texSize;varying vec2 texCoord;"+r+"void main(){vec4 color=vec4(0.0);float total=0.0;vec2 toCenter=center-texCoord*texSize;float offset=random(vec3(12.9898,78.233,151.7182),0.0);for(float t=0.0;t<=40.0;t++){float percent=(t+offset)/40.0;float weight=4.0*(percent-percent*percent);vec4 sample=texture2D(texture,texCoord+toCenter*percent*strength/texSize);sample.rgb*=sample.a;color+=sample*weight;total+=weight;}gl_FragColor=color/total;gl_FragColor.rgb/=gl_FragColor.a+0.00001;}");
g.call(this,a.zoomBlur,{center:[b,d],strength:c,texSize:[this.width,this.height]});return this}function ca(b,d,c,e){a.colorHalftone=a.colorHalftone||new h(null,"uniform sampler2D texture;uniform vec2 center;uniform float angle;uniform float scale;uniform vec2 texSize;varying vec2 texCoord;float pattern(float angle){float s=sin(angle),c=cos(angle);vec2 tex=texCoord*texSize-center;vec2 point=vec2(c*tex.x-s*tex.y,s*tex.x+c*tex.y)*scale;return(sin(point.x)*sin(point.y))*4.0;}void main(){vec4 color=texture2D(texture,texCoord);vec3 cmy=1.0-color.rgb;float k=min(cmy.x,min(cmy.y,cmy.z));cmy=(cmy-k)/(1.0-k);cmy=clamp(cmy*10.0-3.0+vec3(pattern(angle+0.26179),pattern(angle+1.30899),pattern(angle)),0.0,1.0);k=clamp(k*10.0-5.0+pattern(angle+0.78539),0.0,1.0);gl_FragColor=vec4(1.0-cmy-k,color.a);}");
g.call(this,a.colorHalftone,{center:[b,d],angle:c,scale:Math.PI/e,texSize:[this.width,this.height]});return this}function da(b,d,c,e){a.dotScreen=a.dotScreen||new h(null,"uniform sampler2D texture;uniform vec2 center;uniform float angle;uniform float scale;uniform vec2 texSize;varying vec2 texCoord;float pattern(){float s=sin(angle),c=cos(angle);vec2 tex=texCoord*texSize-center;vec2 point=vec2(c*tex.x-s*tex.y,s*tex.x+c*tex.y)*scale;return(sin(point.x)*sin(point.y))*4.0;}void main(){vec4 color=texture2D(texture,texCoord);float average=(color.r+color.g+color.b)/3.0;gl_FragColor=vec4(vec3(average*10.0-5.0+pattern()),color.a);}");
g.call(this,a.dotScreen,{center:[b,d],angle:c,scale:Math.PI/e,texSize:[this.width,this.height]});return this}function ea(b){a.edgeWork1=a.edgeWork1||new h(null,"uniform sampler2D texture;uniform vec2 delta;varying vec2 texCoord;"+r+"void main(){vec2 color=vec2(0.0);vec2 total=vec2(0.0);float offset=random(vec3(12.9898,78.233,151.7182),0.0);for(float t=-30.0;t<=30.0;t++){float percent=(t+offset-0.5)/30.0;float weight=1.0-abs(percent);vec3 sample=texture2D(texture,texCoord+delta*percent).rgb;float average=(sample.r+sample.g+sample.b)/3.0;color.x+=average*weight;total.x+=weight;if(abs(t)<15.0){weight=weight*2.0-1.0;color.y+=average*weight;total.y+=weight;}}gl_FragColor=vec4(color/total,0.0,1.0);}");
a.edgeWork2=a.edgeWork2||new h(null,"uniform sampler2D texture;uniform vec2 delta;varying vec2 texCoord;"+r+"void main(){vec2 color=vec2(0.0);vec2 total=vec2(0.0);float offset=random(vec3(12.9898,78.233,151.7182),0.0);for(float t=-30.0;t<=30.0;t++){float percent=(t+offset-0.5)/30.0;float weight=1.0-abs(percent);vec2 sample=texture2D(texture,texCoord+delta*percent).xy;color.x+=sample.x*weight;total.x+=weight;if(abs(t)<15.0){weight=weight*2.0-1.0;color.y+=sample.y*weight;total.y+=weight;}}float c=clamp(10000.0*(color.y/total.y-color.x/total.x)+0.5,0.0,1.0);gl_FragColor=vec4(c,c,c,1.0);}");
g.call(this,a.edgeWork1,{delta:[b/this.width,0]});g.call(this,a.edgeWork2,{delta:[0,b/this.height]});return this}function fa(b,d,c){a.hexagonalPixelate=a.hexagonalPixelate||new h(null,"uniform sampler2D texture;uniform vec2 center;uniform float scale;uniform vec2 texSize;varying vec2 texCoord;void main(){vec2 tex=(texCoord*texSize-center)/scale;tex.y/=0.866025404;tex.x-=tex.y*0.5;vec2 a;if(tex.x+tex.y-floor(tex.x)-floor(tex.y)<1.0)a=vec2(floor(tex.x),floor(tex.y));else a=vec2(ceil(tex.x),ceil(tex.y));vec2 b=vec2(ceil(tex.x),floor(tex.y));vec2 c=vec2(floor(tex.x),ceil(tex.y));vec3 TEX=vec3(tex.x,tex.y,1.0-tex.x-tex.y);vec3 A=vec3(a.x,a.y,1.0-a.x-a.y);vec3 B=vec3(b.x,b.y,1.0-b.x-b.y);vec3 C=vec3(c.x,c.y,1.0-c.x-c.y);float alen=length(TEX-A);float blen=length(TEX-B);float clen=length(TEX-C);vec2 choice;if(alen<blen){if(alen<clen)choice=a;else choice=c;}else{if(blen<clen)choice=b;else choice=c;}choice.x+=choice.y*0.5;choice.y*=0.866025404;choice*=scale/texSize;gl_FragColor=texture2D(texture,choice+center/texSize);}");
g.call(this,a.hexagonalPixelate,{center:[b,d],scale:c,texSize:[this.width,this.height]});return this}function ha(){a.toHSV=a.toHSV||new h(null,"uniform sampler2D texture;varying vec2 texCoord;void main(){vec4 color=texture2D(texture,texCoord);if(texCoord.y>0.5){float min=color.r;float max=color.r;if(color.g<min){min=color.g;}if(color.g>max){max=color.g;}if(color.b<min){min=color.b;}if(color.b>max){max=color.b;}float delta=max-min;float s=0.0;float h=0.0;float v=max;if(max!=0.0){s=delta/max;if(color. r==max){h=(color.g-color.b)/delta;}else if(color.g==max){h=2.0+(color.b-color.r)/delta;}else{h=4.0+(color.r-color.g)/delta;}h=h*60.0;if(h<0.0)h=h+360.0;}color.r=h/360.0;color.g=s;color.b=v;}gl_FragColor=color;}");
g.call(this,a.toHSV,{});return this}function ia(b){a.ink=a.ink||new h(null,"uniform sampler2D texture;uniform float strength;uniform vec2 texSize;varying vec2 texCoord;void main(){vec2 dx=vec2(1.0/texSize.x,0.0);vec2 dy=vec2(0.0,1.0/texSize.y);vec4 color=texture2D(texture,texCoord);float bigTotal=0.0;float smallTotal=0.0;vec3 bigAverage=vec3(0.0);vec3 smallAverage=vec3(0.0);for(float x=-2.0;x<=2.0;x+=1.0){for(float y=-2.0;y<=2.0;y+=1.0){vec3 sample=texture2D(texture,texCoord+dx*x+dy*y).rgb;bigAverage+=sample;bigTotal+=1.0;if(abs(x)+abs(y)<2.0){smallAverage+=sample;smallTotal+=1.0;}}}vec3 edge=max(vec3(0.0),bigAverage/bigTotal-smallAverage/smallTotal);gl_FragColor=vec4(color.rgb-dot(edge,edge)*strength*100000.0,color.a);}");
g.call(this,a.ink,{strength:b*b*b*b*b,texSize:[this.width,this.height]});return this}function ja(){a.invertColor=a.invertColor||new h(null,"uniform sampler2D texture;varying vec2 texCoord;void main(){vec4 color=texture2D(texture,texCoord);color.rgb=1.0-color.rgb;gl_FragColor=color;}");g.call(this,a.invertColor,{});return this}function ka(){a.mirror=a.mirror||new h(null,"uniform sampler2D texture;uniform float brightness;varying vec2 texCoord;void main(){vec4 color=texture2D(texture,vec2(1.0-texCoord.x,texCoord.y));gl_FragColor=color;}");
g.call(this,a.mirror,{});return this}function la(b,d,c,e,k,f,m,t,p,n,q){a.sobel=a.sobel||new h(null,"uniform sampler2D texture;uniform float alpha;uniform float r;uniform float g;uniform float b;uniform float r2;uniform float g2;uniform float b2;uniform float a2;uniform float a;uniform float secondary;uniform float coef;varying vec2 texCoord;void main(){vec4 color=texture2D(texture,texCoord);float bottomLeftIntensity=texture2D(texture,texCoord+vec2(-0.0015625,0.0020833)).r;float topRightIntensity=texture2D(texture,texCoord+vec2(0.0015625,-0.0020833)).r;float topLeftIntensity=texture2D(texture,texCoord+vec2(-0.0015625,0.0020833)).r;float bottomRightIntensity=texture2D(texture,texCoord+vec2(0.0015625,0.0020833)).r;float leftIntensity=texture2D(texture,texCoord+vec2(-0.0015625,0)).r;float rightIntensity=texture2D(texture,texCoord+vec2(0.0015625,0)).r;float bottomIntensity=texture2D(texture,texCoord+vec2(0,0.0020833)).r;float topIntensity=texture2D(texture,texCoord+vec2(0,-0.0020833)).r;float h=-secondary*topLeftIntensity-coef*topIntensity-secondary*topRightIntensity+secondary*bottomLeftIntensity+coef*bottomIntensity+secondary*bottomRightIntensity;float v=-secondary*bottomLeftIntensity-coef*leftIntensity-secondary*topLeftIntensity+secondary*bottomRightIntensity+coef*rightIntensity+secondary*topRightIntensity;float mag=length(vec2(h,v));if(mag<0.5){float al=alpha*a;color.rgb*=(1.0-al);color.r+=r*al;color.g+=g*al;color.b+=b*al;color.rgb+=al*mag;}else{float al=alpha*a2;color.rgb*=(1.0-al);color.r+=r2*al;color.g+=g2*al;color.b+=b2*al;color.rgb+=al*mag;}gl_FragColor=color;}");
g.call(this,a.sobel,{secondary:b,coef:d,alpha:c,r:e,g:k,b:f,a:m,r2:t,g2:p,b2:n,a2:q});return this}function ma(b,d,c,e){a.bulgePinch=a.bulgePinch||v("uniform float radius;uniform float strength;uniform vec2 center;","coord-=center;float distance=length(coord);if(distance<radius){float percent=distance/radius;if(strength>0.0){coord*=mix(1.0,smoothstep(0.0,radius/distance,percent),strength*0.75);}else{coord*=mix(1.0,pow(percent,1.0+strength*0.75)*radius/distance,1.0-percent);}}coord+=center;");
g.call(this,a.bulgePinch,{radius:c,strength:n(-1,e,1),center:[b,d],texSize:[this.width,this.height]});return this}function na(b,d,c){a.matrixWarp=a.matrixWarp||v("uniform mat3 matrix;uniform bool useTextureSpace;","if(useTextureSpace)coord=coord/texSize*2.0-1.0;vec3 warp=matrix*vec3(coord,1.0);coord=warp.xy/warp.z;if(useTextureSpace)coord=(coord*0.5+0.5)*texSize;");b=Array.prototype.concat.apply([],b);if(4==b.length)b=
[b[0],b[1],0,b[2],b[3],0,0,0,1];else if(9!=b.length)throw"can only warp with 2x2 or 3x3 matrix";g.call(this,a.matrixWarp,{matrix:d?z(b):b,texSize:[this.width,this.height],useTextureSpace:c|0});return this}function oa(a,d){d=y.apply(null,d);a=y.apply(null,a);d=z(d);return this.matrixWarp([d[0]*a[0]+d[1]*a[3]+d[2]*a[6],d[0]*a[1]+d[1]*a[4]+d[2]*a[7],d[0]*a[2]+d[1]*a[5]+d[2]*a[8],d[3]*a[0]+d[4]*a[3]+d[5]*a[6],d[3]*a[1]+d[4]*a[4]+d[5]*a[7],d[3]*a[2]+d[4]*a[5]+d[5]*a[8],d[6]*a[0]+d[7]*a[3]+d[8]*a[6],d[6]*
a[1]+d[7]*a[4]+d[8]*a[7],d[6]*a[2]+d[7]*a[5]+d[8]*a[8]])}function pa(b,d,c,e){a.swirl=a.swirl||v("uniform float radius;uniform float angle;uniform vec2 center;","coord-=center;float distance=length(coord);if(distance<radius){float percent=(radius-distance)/radius;float theta=percent*percent*angle;float s=sin(theta);float c=cos(theta);coord=vec2(coord.x*c-coord.y*s,coord.x*s+coord.y*c);}coord+=center;");
g.call(this,a.swirl,{radius:c,center:[b,d],angle:e,texSize:[this.width,this.height]});return this}var w={};(function(){function a(){}function d(b){"OES_texture_float_linear"===b?(void 0===this.$OES_texture_float_linear$&&Object.defineProperty(this,"$OES_texture_float_linear$",{enumerable:!1,configurable:!1,writable:!1,value:new a}),b=this.$OES_texture_float_linear$):b=k.call(this,b);return b}function c(){var a=f.call(this);-1===a.indexOf("OES_texture_float_linear")&&a.push("OES_texture_float_linear");
return a}try{var e=document.createElement("canvas").getContext("experimental-webgl")}catch(m){}if(e&&-1===e.getSupportedExtensions().indexOf("OES_texture_float_linear")&&function(a){if(!a.getExtension("OES_texture_float"))return!1;var b=a.createFramebuffer(),c=a.createTexture();a.bindTexture(a.TEXTURE_2D,c);a.texParameteri(a.TEXTURE_2D,a.TEXTURE_MAG_FILTER,a.NEAREST);a.texParameteri(a.TEXTURE_2D,a.TEXTURE_MIN_FILTER,a.NEAREST);a.texParameteri(a.TEXTURE_2D,a.TEXTURE_WRAP_S,a.CLAMP_TO_EDGE);a.texParameteri(a.TEXTURE_2D,
a.TEXTURE_WRAP_T,a.CLAMP_TO_EDGE);a.texImage2D(a.TEXTURE_2D,0,a.RGBA,1,1,0,a.RGBA,a.UNSIGNED_BYTE,null);a.bindFramebuffer(a.FRAMEBUFFER,b);a.framebufferTexture2D(a.FRAMEBUFFER,a.COLOR_ATTACHMENT0,a.TEXTURE_2D,c,0);b=a.createTexture();a.bindTexture(a.TEXTURE_2D,b);a.texParameteri(a.TEXTURE_2D,a.TEXTURE_MAG_FILTER,a.LINEAR);a.texParameteri(a.TEXTURE_2D,a.TEXTURE_MIN_FILTER,a.LINEAR);a.texParameteri(a.TEXTURE_2D,a.TEXTURE_WRAP_S,a.CLAMP_TO_EDGE);a.texParameteri(a.TEXTURE_2D,a.TEXTURE_WRAP_T,a.CLAMP_TO_EDGE);
a.texImage2D(a.TEXTURE_2D,0,a.RGBA,2,2,0,a.RGBA,a.FLOAT,new Float32Array([2,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]));c=a.createProgram();var e=a.createShader(a.VERTEX_SHADER),d=a.createShader(a.FRAGMENT_SHADER);a.shaderSource(e,"attribute vec2 vertex;void main(){gl_Position=vec4(vertex,0.0,1.0);}");a.shaderSource(d,"uniform sampler2D texture;void main(){gl_FragColor=texture2D(texture,vec2(0.5));}");a.compileShader(e);a.compileShader(d);
a.attachShader(c,e);a.attachShader(c,d);a.linkProgram(c);e=a.createBuffer();a.bindBuffer(a.ARRAY_BUFFER,e);a.bufferData(a.ARRAY_BUFFER,new Float32Array([0,0]),a.STREAM_DRAW);a.enableVertexAttribArray(0);a.vertexAttribPointer(0,2,a.FLOAT,!1,0,0);e=new Uint8Array(4);a.useProgram(c);a.viewport(0,0,1,1);a.bindTexture(a.TEXTURE_2D,b);a.drawArrays(a.POINTS,0,1);a.readPixels(0,0,1,1,a.RGBA,a.UNSIGNED_BYTE,e);return 127===e[0]||128===e[0]}(e)){var k=WebGLRenderingContext.prototype.getExtension,f=WebGLRenderingContext.prototype.getSupportedExtensions;
WebGLRenderingContext.prototype.getExtension=d;WebGLRenderingContext.prototype.getSupportedExtensions=c}})();var a;w.canvas=function(){var b=document.createElement("canvas");try{a=b.getContext("experimental-webgl",{premultipliedAlpha:!1})}catch(d){a=null}if(!a)throw"This browser does not support WebGL";b._={gl:a,isInitialized:!1,texture:null,spareTexture:null,flippedShader:null};b.texture=f(B);b.draw=f(D);b.update=f(E);b.replace=f(F);b.contents=f(G);b.getPixelArray=f(H);b.brightnessContrast=f(I);
b.hexagonalPixelate=f(fa);b.hueSaturation=f(R);b.colorHalftone=f(ca);b.triangleBlur=f(aa);b.unsharpMask=f(V);b.perspective=f(oa);b.matrixWarp=f(na);b.bulgePinch=f(ma);b.tiltShift=f(Z);b.dotScreen=f(da);b.edgeWork=f(ea);b.lensBlur=f(Y);b.zoomBlur=f(ba);b.noise=f(S);b.denoise=f(M);b.curves=f(L);b.swirl=f(pa);b.ink=f(ia);b.vignette=f(X);b.vibrance=f(W);b.sepia=f(T);b.coloradjust=f(K);b.color=f(J);b.exposure=f(N);b.gamma=f(O);b.gammaRGB=f(P);b.hue=f(Q);b.sobel=f(la);b.softContrast=f(U);b.toHSV=f(ha);
b.invertColor=f(ja);b.mirror=f(ka);return b};w.splineInterpolate=u;var h=function(){function b(b,e){b=a.createShader(b);a.shaderSource(b,e);a.compileShader(b);if(!a.getShaderParameter(b,a.COMPILE_STATUS))throw"compile error: "+a.getShaderInfoLog(b);return b}function d(c,e){this.texCoordAttribute=this.vertexAttribute=null;this.program=a.createProgram();e="precision highp float;"+(e||"uniform sampler2D texture;varying vec2 texCoord;void main(){gl_FragColor=texture2D(texture,texCoord);}");
a.attachShader(this.program,b(a.VERTEX_SHADER,c||"attribute vec2 vertex;attribute vec2 _texCoord;varying vec2 texCoord;void main(){texCoord=_texCoord;gl_Position=vec4(vertex*2.0-1.0,0.0,1.0);}"));a.attachShader(this.program,b(a.FRAGMENT_SHADER,e));a.linkProgram(this.program);if(!a.getProgramParameter(this.program,a.LINK_STATUS))throw"link error: "+a.getProgramInfoLog(this.program);}d.prototype.destroy=function(){a.deleteProgram(this.program);this.program=
null};d.prototype.uniforms=function(b){a.useProgram(this.program);for(var e in b)if(b.hasOwnProperty(e)){var c=a.getUniformLocation(this.program,e);if(null!==c){var d=b[e];if("[object Array]"==Object.prototype.toString.call(d))switch(d.length){case 1:a.uniform1fv(c,new Float32Array(d));break;case 2:a.uniform2fv(c,new Float32Array(d));break;case 3:a.uniform3fv(c,new Float32Array(d));break;case 4:a.uniform4fv(c,new Float32Array(d));break;case 9:a.uniformMatrix3fv(c,!1,new Float32Array(d));break;case 16:a.uniformMatrix4fv(c,
!1,new Float32Array(d));break;default:throw"dont't know how to load uniform \""+e+'" of length '+d.length;}else if("[object Number]"==Object.prototype.toString.call(d))a.uniform1f(c,d);else throw'attempted to set uniform "'+e+'" to invalid value '+(d||"undefined").toString();}}return this};d.prototype.textures=function(b){a.useProgram(this.program);for(var e in b)b.hasOwnProperty(e)&&a.uniform1i(a.getUniformLocation(this.program,e),b[e]);return this};d.prototype.drawRect=function(b,e,d,f){var c=a.getParameter(a.VIEWPORT);
e=void 0!==e?(e-c[1])/c[3]:0;b=void 0!==b?(b-c[0])/c[2]:0;d=void 0!==d?(d-c[0])/c[2]:1;f=void 0!==f?(f-c[1])/c[3]:1;null==a.vertexBuffer&&(a.vertexBuffer=a.createBuffer());a.bindBuffer(a.ARRAY_BUFFER,a.vertexBuffer);a.bufferData(a.ARRAY_BUFFER,new Float32Array([b,e,b,f,d,e,d,f]),a.STATIC_DRAW);null==a.texCoordBuffer&&(a.texCoordBuffer=a.createBuffer(),a.bindBuffer(a.ARRAY_BUFFER,a.texCoordBuffer),a.bufferData(a.ARRAY_BUFFER,new Float32Array([0,0,0,1,1,0,1,1]),a.STATIC_DRAW));null==this.vertexAttribute&&
(this.vertexAttribute=a.getAttribLocation(this.program,"vertex"),a.enableVertexAttribArray(this.vertexAttribute));null==this.texCoordAttribute&&(this.texCoordAttribute=a.getAttribLocation(this.program,"_texCoord"),a.enableVertexAttribArray(this.texCoordAttribute));a.useProgram(this.program);a.bindBuffer(a.ARRAY_BUFFER,a.vertexBuffer);a.vertexAttribPointer(this.vertexAttribute,2,a.FLOAT,!1,0,0);a.bindBuffer(a.ARRAY_BUFFER,a.texCoordBuffer);a.vertexAttribPointer(this.texCoordAttribute,2,a.FLOAT,!1,
0,0);a.drawArrays(a.TRIANGLE_STRIP,0,4)};d.getDefaultShader=function(){a.defaultShader=a.defaultShader||new d;return a.defaultShader};return d}();A.prototype.interpolate=function(a){for(var b=0,c=this.ya.length-1;1<c-b;){var e=c+b>>1;this.xa[e]>a?c=e:b=e}e=this.xa[c]-this.xa[b];var f=(this.xa[c]-a)/e;a=(a-this.xa[b])/e;return f*this.ya[b]+a*this.ya[c]+((f*f*f-f)*this.y2[b]+(a*a*a-a)*this.y2[c])*e*e/6};var q=function(){function b(b,c,d,f){this.gl=a;this.id=a.createTexture();this.width=b;this.height=
c;this.format=d;this.type=f;a.bindTexture(a.TEXTURE_2D,this.id);a.texParameteri(a.TEXTURE_2D,a.TEXTURE_MAG_FILTER,a.LINEAR);a.texParameteri(a.TEXTURE_2D,a.TEXTURE_MIN_FILTER,a.LINEAR);a.texParameteri(a.TEXTURE_2D,a.TEXTURE_WRAP_S,a.CLAMP_TO_EDGE);a.texParameteri(a.TEXTURE_2D,a.TEXTURE_WRAP_T,a.CLAMP_TO_EDGE);b&&c&&a.texImage2D(a.TEXTURE_2D,0,this.format,b,c,0,this.format,this.type,null)}function d(a){null==c&&(c=document.createElement("canvas"));c.width=a.width;c.height=a.height;a=c.getContext("2d");
a.clearRect(0,0,c.width,c.height);return a}b.fromElement=function(c){var d=new b(0,0,a.RGBA,a.UNSIGNED_BYTE);d.loadContentsOf(c);return d};b.prototype.loadContentsOf=function(b){this.width=b.width||b.videoWidth;this.height=b.height||b.videoHeight;a.bindTexture(a.TEXTURE_2D,this.id);a.texImage2D(a.TEXTURE_2D,0,this.format,this.format,this.type,b)};b.prototype.initFromBytes=function(b,c,d){this.width=b;this.height=c;this.format=a.RGBA;this.type=a.UNSIGNED_BYTE;a.bindTexture(a.TEXTURE_2D,this.id);a.texImage2D(a.TEXTURE_2D,
0,a.RGBA,b,c,0,a.RGBA,this.type,new Uint8Array(d))};b.prototype.destroy=function(){a.deleteTexture(this.id);this.id=null};b.prototype.use=function(b){a.activeTexture(a.TEXTURE0+(b||0));a.bindTexture(a.TEXTURE_2D,this.id)};b.prototype.unuse=function(b){a.activeTexture(a.TEXTURE0+(b||0));a.bindTexture(a.TEXTURE_2D,null)};b.prototype.ensureFormat=function(b,c,d,f){if(1==arguments.length){var e=arguments[0];b=e.width;c=e.height;d=e.format;f=e.type}if(b!=this.width||c!=this.height||d!=this.format||f!=
this.type)this.width=b,this.height=c,this.format=d,this.type=f,a.bindTexture(a.TEXTURE_2D,this.id),a.texImage2D(a.TEXTURE_2D,0,this.format,b,c,0,this.format,this.type,null)};b.prototype.drawTo=function(b){a.framebuffer=a.framebuffer||a.createFramebuffer();a.bindFramebuffer(a.FRAMEBUFFER,a.framebuffer);a.framebufferTexture2D(a.FRAMEBUFFER,a.COLOR_ATTACHMENT0,a.TEXTURE_2D,this.id,0);if(a.checkFramebufferStatus(a.FRAMEBUFFER)!==a.FRAMEBUFFER_COMPLETE)throw Error("incomplete framebuffer");a.viewport(0,
0,this.width,this.height);b();a.bindFramebuffer(a.FRAMEBUFFER,null)};var c=null;b.prototype.fillUsingCanvas=function(b){b(d(this));this.format=a.RGBA;this.type=a.UNSIGNED_BYTE;a.bindTexture(a.TEXTURE_2D,this.id);a.texImage2D(a.TEXTURE_2D,0,a.RGBA,a.RGBA,a.UNSIGNED_BYTE,c);return this};b.prototype.toImage=function(b){this.use();h.getDefaultShader().drawRect();var e=this.width*this.height*4,f=new Uint8Array(e),g=d(this),n=g.createImageData(this.width,this.height);a.readPixels(0,0,this.width,this.height,
a.RGBA,a.UNSIGNED_BYTE,f);for(var p=0;p<e;p++)n.data[p]=f[p];g.putImageData(n,0,0);b.src=c.toDataURL()};b.prototype.swapWith=function(a){var b=a.id;a.id=this.id;this.id=b;b=a.width;a.width=this.width;this.width=b;b=a.height;a.height=this.height;this.height=b;b=a.format;a.format=this.format;this.format=b};return b}(),r="float random(vec3 scale,float seed){return fract(sin(dot(gl_FragCoord.xyz+seed,scale))*43758.5453+seed);}";
return w}();
